apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-gatekeeper-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  maxReplicas: {{ .Values.controllerManager.autoscaling.maxReplicas }}
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: {{ .Values.controllerManager.autoscaling.targetCPUUtilizationPercentage }}
    type: Resource
  minReplicas: {{ .Values.controllerManager.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gatekeeper-controller-manager
